### ISSUE TITLE
FE 프로젝트 초기화

### ISSUE THREAD

**Issue by MayOwall** [MayOwall/one-thing-todo-app#1]
### 설명

프로젝트 초기화

### Todo

- [x] dev 브랜치 생성
- [x] FE 폴더 생성
- [x] 번들러 적용
- [x] 프로젝트 실행 확인
- [ ] 테스트용 서버 배포
