### ISSUE TITLE
리스트 페이지 - 리스트 아이템 생성

### ISSUE THREAD

**Issue by MayOwall** [MayOwall/one-thing-todo-app#11]
### 설명

아토믹 디자인 시스템을 통해 리스트 컴포넌트를 생성합니다.

### 디자인

<img src='https://github.com/MayOwall/one-thing-todo-app/assets/97934878/0844416b-710b-452c-a106-701a84b1f823' height=700 />

### Todo

- [ ] 리스트 컴포넌트용 더미데이터 생성
- [ ] 리스트 아이템 컴포넌트 생성
- [ ] 리스트 컴포넌트 생성
